# Generated by Django 4.1.5 on 2023-01-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idbook', models.CharField(max_length=30)),
                ('nameofbook', models.CharField(max_length=60)),
                ('authorofbook', models.CharField(max_length=60)),
                ('priceofbook', models.CharField(max_length=20)),
            ],
        ),
    ]
