# Generated by Django 4.1.5 on 2023-01-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksinventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('idbook', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameofbook', models.CharField(max_length=60)),
                ('authorofbook', models.CharField(max_length=60)),
                ('priceofbook', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='BookInventory',
        ),
    ]
